export const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAINT: "P2002",
  RECORD_NOT_FOUND: "P2025",
  FOREIGN_KEY_CONSTRAINT: "P2003",
  NULL_CONSTRAINT: "P2011",
  RELATION_NOT_FOUND: "P2018",
  REQUIRED_CONNECTED_RECORD_NOT_FOUND: "P2015",
} as const;
